### ISSUE TITLE
Create Crypto Package

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/oos-utils#112]
Include SHA-1 and SHA-2 functions. Purpose is remove reliance on `dbms_crypto` package for `oos_util_totp`

http://www.movable-type.co.uk/scripts/sha1.html

**Comment by Sam-Hall** [comment]
Check out this project... https://github.com/vadimonus/plsql-hash

**Comment by antonscheffer** [comment]
Check out this project https://github.com/antonscheffer/as_crypto
It's a complete replacement for dbms_crypto. It only lacks handling of blob/clob values

**Comment by martindsouza** [comment]
@antonscheffer I'd really like to integrate your project over just need your permission to do so. I'm trying to avoid having a bunch of different licences on this project. Are you ok if I merge your code in without including your license file? Our project is under the MIT license so end users only need to abide by that one.

**Comment by antonscheffer** [comment]
That’s OK

Met vriendelijke groeten,
Anton Scheffer
Senior Java Developer
[AMIS25 email]

M

+31 6 41 01 02 98

E

amis.nl<http://www.amis.nl/>

[Oracle Platinum Partner]

**Comment by martindsouza** [comment]
@antonscheffer great. I'll merge it in. Some slight modifications will be required to fit with the OOS standards. Once it's in, are you ok with referencing the OOS Utils package and maintaining it rather than having 2 copies out there? (that's the goal of OOS Utils).
