### ISSUE TITLE
Use oos_util_crypto for SHA-1 Hash in TOTP

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/oos-utils#113]
Dependant on #112 

https://github.com/antonscheffer/as_crypto

**Comment by Sam-Hall** [comment]
Here's an alternative OTP package I developed a couple years back, you're welcome to use this... https://gist.github.com/Sam-Hall/72eb8a5bf0cc6be72371267a540d4cc6

This package only has functions to work with the OTP key and timestamp generation and leaves the SHA-1 crypto call up to the implementation, which might be good if you're planning to replace that anyway. It's also more efficient, as it doesn't rely on string manipulation techniques to process the keys.

Here's a sample usage...

> set serveroutput on;
>   
> declare
>   l_timestamp NUMBER := OTP.get_timestamp;
>   l_hex_time  varchar2(16) := LPAD(TRIM(TO_CHAR(l_timestamp,'XXXXXXXXXXXXXXXX')),16,'0');
>   l_raw_time  RAW(8);
>   l_raw_key   RAW(10) := OTP.DECODE_KEY('XHOHUVU2B5KGVXIX');
>   l_raw_otp   RAW(20);
> begin
>   l_raw_time := HEXTORAW(l_hex_time);
>     
>   dbms_output.put_line(l_hex_time);
>     
>   L_RAW_OTP := sys.dbms_crypto.MAC(l_raw_time, sys.dbms_crypto.hmac_sh1, l_raw_key);
>     
>   dbms_output.put_line(L_RAW_OTP);
>    
>   dbms_output.put_line(OTP.HASH_TO_CODE(L_RAW_OTP));
> end;
