### ISSUE TITLE
Regarding your default date format

### ISSUE THREAD

**Issue by stevenfeuerstein** [OraOpenSource/oos-utils#121]
Why not follow the DATE literal format: YYYY-MM-DD

You avoid using text for months, it is more universally followed, I think.

**Comment by janihur** [comment]
YYYY-MM-DD is ISO 8601 (https://en.wikipedia.org/wiki/ISO_8601) and also used in XML Schema (https://www.w3.org/TR/xmlschema-2/#isoformats) too.

**Comment by martindsouza** [comment]
@stevenfeuerstein thanks for the feedback. I really hate `YYYY-MM-DD` as it's hard to know is it `MM-DD` or `DD-MM` (and yes people have done both my past experiences). That said it's community driven project and @janihur pointed out that it's an ISO standard so we'll make the switch for 1.0.0
