### ISSUE TITLE
oos_util_date.date2epoch and oos_util_date.epoch2date are one hour off

### ISSUE THREAD

**Issue by antonscheffer** [OraOpenSource/oos-utils#123]
oos_util_date.date2epoch and oos_util_date.epoch2date are one hour off.

Maybe
function date2epoch( p_date in date )
return number
as
begin
  return round( ( p_date - date '1970-01-01' ) * 86400 )
       - extract( timezone_hour from current_timestamp ) * 3600
       - extract( timezone_minute from current_timestamp ) * 60;
end date2epoch;

function epoch2date( p_epoch in number )
return date
as
begin
  return date '1970-01-01' + p_epoch / 86400
       + extract( timezone_hour from current_timestamp ) / 24
       + extract( timezone_minute from current_timestamp ) / 1440;
end epoch2date;

**Comment by martindsouza** [comment]
Fixed. Thanks for the code sample and raising the issue.
