### ISSUE TITLE
oos_util_string.sprintf should receive a collection instead of 10 string arguments

### ISSUE THREAD

**Issue by Nunalves** [OraOpenSource/oos-utils#134]
I know this is not the place to say this, but first of all i wanna thank all of the team working on this project and others from OraOpenSource, you've made my life a lot easier. I wanna contribute to this specific project because i think i can be of help.

Back to the issue, the 10 vars string replacement limit does not make much sense. The oos_util_string.sprintf function should receive a nested table of key/value pairs where the user could specify the key to be replaced by the value. This way the function would allow for more flexibility and reuse.

I can do it if you guys would accept the pull request :)

**Comment by zhudock** [comment]
I'd be interested in seeing your implementation. My only suggestion would be that the function supports both the key/value pair and replacing in position order.

**Comment by martindsouza** [comment]
@Nunalves I appreciate your feedback on the `sprintf` function. I acknowledge that passing in a nested table (similar to the `params`) would allow unlimited replacement strings. 

My concern around such an approach is that it would involve an additional step (load the key/value pairs) and my not work from an sql statement. Do you see any ways around this?

**Comment by Nunalves** [comment]
Hi guys, thanks for the responses, i made a quick implementation. will commit it here.
@zhudock it covers both your suggestions, replacement by key/value pairs and by position.
@martindsouza it also can be used in a sql statement by instantiating the types directly on the function parameters.

It would be used like this:

1. key/value pair replacing
```
SELECT oos_util_string.sprintf('Hello {firstName} {lastName}!', 
                                t_tab_key_value(t_rec_key_value('firstName', 'Nuno'),
                                                t_rec_key_value('lastName', 'Alves')
                                                )
                              ) demo
FROM dual;
```

2. replacing in position order:
```
select oos_util_string.sprintf('hello {1} {2}!', t_tab_vc2('Nuno','Alves')) demo
from dual;
```

this second also supports changing the positions in the string:
```
select oos_util_string.sprintf('hello {2} {1}!', t_tab_vc2('Nuno','Alves')) demo
from dual;
```

I know that it isn't the same pattern used, but the function also allows changing the default pattern (left string and right string for enclosing pattern), giving users more flexibility, so they can even keep using the '%s' pattern like this:

```
select oos_util_string.sprintf('hello %s1 %s2!', t_tab_vc2('Nuno','Alves'), '%s','') demo
from dual;
```

This would also allow us to internally use the same function on the old sprintf for legacy purposes, the only drawback is that my functions currently don't support the passing a string not "labeled" or "numbered" like you would on the currently sprintf. But in my opinion that's also not a good practice and can lead to bugs on the user side because he has to manually count the parameters on a string and pass its values on the right position, which can be a "find wally" kind of thing on big strings, like this: ''

`select oos_util_string.sprintf('Lorem ipsum dolor sit amet, consectetur %s elit. Quisque id neque non mi varius sagittis. %s ipsum massa, suscipit sed est in, consequat vehicula neque. Donec dictum vehicula %s. Cras suscipit tincidunt malesuada. Suspendisse potenti. Nullam eget lorem id urna eleifend faucibus quis sit amet ex. Donec ac ante laoreet, tincidunt ex vel, cursus ligula. Ut pulvinar tempor quam, in porta %s pretium vel. Fusce vulputate malesuada pharetra. Vestibulum faucibus nibh ligula, eu convallis est %s et. Praesent non erat sodales, facilisis ligula in, lobortis ex. Phasellus eu ornare nulla. Suspendisse potenti. Nulla vehicula dignissim eros.','adipiscing','Donec','eleifend','nibh','suscipit') demo
from dual;`

I'll make a pull request with the code, for now i left the old sprintf function intact, maybe you guys will want to keep it like that for legacy purposes.

 
## Function signatures

```
  function sprintf(
    p_str in varchar2,
    p_key_values in t_tab_key_value,
    p_left_pattern in varchar2 default '{',
    p_right_pattern in varchar2 default '}')
    return varchar2;
    
  function sprintf(
    p_str in varchar2,
    p_tab_vc2 in t_tab_vc2,
    p_left_pattern in varchar2 default '{',
    p_right_pattern in varchar2 default '}')
    return varchar2;
```

**Comment by martindsouza** [comment]
@Nunalves Thanks for the suggestion. This seems like a more advanced version of `sprintf` so it would need to be called something else. I'm going to tag this as a future item as we're trying to close off v1.0.0 now.

**Comment by Nunalves** [comment]
@martindsouza You are welcome

**Comment by Nunalves** [comment]
@martindsouza How would you like me to commit the code then? I will make a pull request, if that's not the right way and i should open a new branch or fork the project, please tell me. (I am used to git and git flow but i've never contributed to a gitHub project before)

**Comment by martindsouza** [comment]
@Nunalves PRs are perfect. I won't accept now as I don't want the code in the main branch for v1.

**Comment by martindsouza** [comment]
Will not be accepting this as it requires a SQL Type. `oos_util_string.multi_replace` can handle similar functionality.
