### ISSUE TITLE
Type Guidelines in OOS Utils

### ISSUE THREAD

**Issue by janihur** [OraOpenSource/oos-utils#139]
We should have a guideline how we introduce (and name) new types before the namespace is polluted with ad hoc decisions (e.g. see #134).

Guideline documentation should take place in Dev Standards section of https://github.com/OraOpenSource/oos-utils/blob/master/build/README.md

I see the following questions:

- Do we prefer common types or package specific types ?
- PL/SQL types vs. SQL types ?

Common types' scope is the whole oos-utils project and all other packages (and oos-users) can use them.

If there is no common types then each package specifies their own types even if the types are essentially identical.

Only PL/SQL types or only SQL types or a mixed combination ? Of course we can also have both as the PL/SQL and SQL type are in different namespace.

Random examples for inspiration:

```
--
-- PL/SQL types in oos_type-package
--

type str_t is varchar2(32767 byte);
type str_list_t is table of str_t;

type num_list_t is table of number;

type str_pair_t is record(
 _1 varchar2(32767 byte)
,_2 varchar2(32767 byte)
);

type str_pair_list is table of str_pair_t;

type str_str_map_t is table of str_t index by str_;
```

```
--
-- SQL types in oos-schema
--

create or replace type str_list_t is table of varchar2(4000 byte);

create or replace type num_list_t is table of number;

create or replace type str_pair_t is object(
 _1 varchar2(4000 byte)
,_2 varchar2(4000 byte)
,map member function comp return number
);

create or replace type str_pair_list_t is table of str_pair_t;
```

**Comment by Nunalves** [comment]
PL/SQL types have the advantage of being organized in packages but they have some limitations when used in a SQL context (on 12c some of them have been improved).

For example, if you had a function returning a PL/SQL table of varchar2 type, you cant do:

SELECT column_value FROM TABLE(pck_example.func_returning_plsql_table_type)

At least on 11g (i'm not sure about 12c but I read that it is now possible), but you can do it if it returns a SQL type. To allow the same functionality on 11g the function would have to iterate the collection and pipe the rows.

There are also other known limitations.
My rule of dumb is to create a SQL type if it is predictable that it will be used in a SQL and PL/SQL context. If i'm quite sure i'll be using the type on a PL/SQL context then i create the type on the package.

**Comment by martindsouza** [comment]
@Nunalves I appreciate the feedback. A few thoughts on previous comment:

* As much as possible we'll try to stay away from adding custom PLSQL types simply to have minimal impact and required privileges on the installed schema. If we absolutely need it we'll do it.
* The statement of package types isn't exactly correct. `oos_util_string.listunagg` can be selected from. From the docs:

```sql
select rownum, column_value
 from table(oos_util_string.listunagg('abc,def'));
```

**Comment by Nunalves** [comment]
I think you wanted to say that you want to avoid SQL types to keep required privileges at a minimum.
oos_util_string.listunagg can be selected from because it is a pipelined table function. It iterates the type collection that it wants to return and uses the 'pipe row' statement. It cannot simply return the collection as is.

**Comment by martindsouza** [comment]
going to close this ticket as I don't think there's anything left to do. Will try our best to avoid using SQL types due to permission requirements.
