### ISSUE TITLE
Should oos_util_lob.get_file_size be in the lob package?

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/oos-utils#142]
Duplicate or move to another package? Has nothing to do with lobs at this point...

**Comment by janihur** [comment]
For some ideas please have a look to `oos_issue_142*` files at https://github.com/janihur/oos-utils-sandbox/

Essentially this is a conversion from a number to more human friendly string presentation of the number. We can think this as a special form of `oos_util_string.to_char(number)` - with a special format models.

This has nothing to do with lobs and never be. I'd suggest `oos_util_string` unless you're planning to have the conversion also other way. In that case it should be a yet another package, e.g. `oos_util_format`.

**Comment by martindsouza** [comment]
Decided to leave in `oos_util_lob` as we don't have another good place to put it. In the future we can support it in two places.
