### ISSUE TITLE
oos_utils_install.sql Permission Checking

### ISSUE THREAD

**Issue by jasonlyle88** [OraOpenSource/oos-utils#148]
Upon running the oos_utils_install.sql script, I noticed that it checks for permissions at the beginning.  However, I ran into some permission issues.  It appears that the permission check does not currently check for permissions for DBMS_CRYPTO and UTL_FILE.  Would be nice to have those added and messages placed about needing them for the dependent objects.

**Comment by zhudock** [comment]
Is DBMS_CRYPTO needed anymore? Looks like it's still in the tests\crypto_test.sql, but doesn't exist anywhere else.

#156 should resolve the UTL_FILE issue as well.

It's possible no changes are needed in the permission check script

**Comment by martindsouza** [comment]
@jasonlyle88 dbms_crypto is no longer required. @zhudock is right we just have it in a test script which is not part of the main install. `oos_util_crypto` replaces the need for it.

`utl_file` will be addressed in a future release.
