### ISSUE TITLE
is_alpha/numeric/alphanumeric

### ISSUE THREAD

**Issue by tschf** [OraOpenSource/oos-utils#15]
e.g. http://www.techonthenet.com/oracle/questions/isnumeric.php

or..
```plsql
function is_numeric(p_str in varchar2) return BOOLEAN
as
    l_num NUMBER;
begin
    l_num := to_number(p_str);

    return true;

exception 
    when value_error
    then 
        return false;
end is_numeric;
```

**Comment by martindsouza** [comment]
What do you think about `is_number` or would you prefer `is_numeric`. We can always do both (one calls the other) and go from there.

**Comment by trent-** [comment]
Either way will be fine. I suggested `is_numeric` just to be consistent with `is_alphanumeric`.

**Comment by martindsouza** [comment]
I called it `is_number` since we'll also have `is_date`. As for `is_alphanumeric` I'll thing of something.

Right now it returns a boolean. Any thoughts/preferences of adding overloaded functions to return a number `1/0` and string `Y/N` or is that overkill for now?

**Comment by tschf** [comment]
I reckon number / y|n version is overkill. Can always add it in the future if there's any interest.

**Comment by martindsouza** [comment]
Won't add `is_alphanumeric` for time being as can easily use regexp `[:alnum:]`
