### ISSUE TITLE
Look-up Tables

### ISSUE THREAD

**Issue by pgunti** [OraOpenSource/oos-utils#16]
Hello Martin,

I would like to add Look-ups and Look-up values (Since I am  from Oracle APPS background using the same terminology) to hold some common values being used in the application. Different set of values for each purpose at place and these can be used for validation or can be   used for LOV etc.,

Please share your thoughts.

Thanks,
Pavan

**Comment by martindsouza** [comment]
Are you looking for a generic name/value table then?

**Comment by martindsouza** [comment]
For now we'll leave out customizing LOVs. May look at it in the future.
