### ISSUE TITLE
Add a p_encode parameter on the function blob2clob 

### ISSUE THREAD

**Issue by jwall-insum** [OraOpenSource/oos-utils#167]
Add a new parameter p_encode as 

` p_encode in varchar2 default dbms_lob.default_csid`

to be used on the parameter blob_csid when calling dbms_lob.converttoclob.

Other options for values:
WE8ISO8859P1
UTF-8
ASCII

**Comment by mdialloinsum** [comment]
Added an extra parameter to the function blob2clob inside of the OOS_UTIL_LOB package:

pks:
    function blob2clob(
    p_blob in blob,
    p_encode in integer default dbms_lob.default_csid)
    return clob;

pkb:
function blob2clob(
    p_blob in blob,
    p_encode in integer default dbms_lob.default_csid)
    return clob
  as
    l_clob clob;
    l_dest_offset integer := 1;
    l_src_offset integer := 1;
    l_lang_context integer := dbms_lob.default_lang_ctx;
    l_warning integer;
    l_encode integer := p_encode;
  begin
    if p_blob is null then
      return null;
    end if;

    dbms_lob.createtemporary(
      lob_loc => l_clob,
      cache => false);

    dbms_lob.converttoclob(
      dest_lob => l_clob,
      src_blob => p_blob,
      amount => dbms_lob.lobmaxsize,
      dest_offset => l_dest_offset,
      src_offset => l_src_offset,
      blob_csid => l_encode,
      lang_context => l_lang_context,
      warning => l_warning);

    oos_util.assert(l_warning = dbms_lob.no_warning, 'failed to convert blob to clob: ' || l_warning);

    return l_clob;
  end blob2clob;

**Comment by martindsouza** [comment]
@jwall-insum I've made this change to path `1.0.1`. Please download [oos_util_install.sql](https://github.com/OraOpenSource/oos-utils/blob/1.1.0/install/oos_utils_install.sql) and test. If it passes we'll cut the `1.0.1` release.
