### ISSUE TITLE
why all the different names for to_Char functions

### ISSUE THREAD

**Issue by Stirl** [OraOpenSource/oos-utils#178]
Why do we have:

TO_CHAR Function
TO_CHAR-1 Function
TO_CHAR-2 Function
TO_CHAR-3 Function
TO_CHAR-4 Function
TO_CHAR-5 Function

Wouldn't it be better to overload using the one name (TO_CHAR would be fine)

**Comment by jeffreykemp** [comment]
The functions are all called to_char.

You may be confused by the documentation, which has "to-char-1", "to-char-2", etc. because this is a limitation of the documentation format which requires unique names.

**Comment by Stirl** [comment]
Yup the doco completely confused me!

**Comment by martindsouza** [comment]
@jeffreykemp summed it up. The tool we're using to generate the documentation automatically adds a number o duplicate function names. 

I'll close this ticket for now as it's low priority and should be fixed in plmddoc
