### ISSUE TITLE
Build Options in OOS_UTIL_APEX

### ISSUE THREAD

**Issue by vitodcampanelli** [OraOpenSource/oos-utils#180]
Are there any plans to implement a function that returns if the build option is enabled?

Example: https://www.talkapex.com/2012/08/integrating-build-options-in-your-plsql/

**Comment by martindsouza** [comment]
See [`apex_util.get_build_option_status`](https://docs.oracle.com/database/apex-5.1/AEAPI/GET_BUILD_OPTION_STATUS-Function-Signature-1.htm#AEAPI29422) _Note there's two signatures for this._ If this is what you're looking for please let me know so we can close this ticket.

**Comment by vitodcampanelli** [comment]
Was looking for something that I can wrap into PL/SQL code to toggle if the code should run or not.
I will try with the above API.
Closing ticket.
