### ISSUE TITLE
Check if an APEX item is rendered or not

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/oos-utils#39]
From @Dani3lSun (#38)

Check if an APEX item is rendered or not (I think Patrick Wolf posted about it some time ago)
https://gist.github.com/Dani3lSun/f5e620e748fb09e1f352

Reason / Example usage: I use it if I have to do custom page level validations (and a item gets not rendered because of an condition or authorization). If using item level validation APEX itself does this check, but on page level a not null validation would fire, because APEX thinks the item is there...

**Comment by martindsouza** [comment]
@Dani3lSun I added a check to ensure that this procedure was only being called on a page submit process. Can you please look it over an ensure you're ok with it.

**Comment by Dani3lSun** [comment]
@martindsouza looks fine! Good idea to call it only when a page gets submitted!
