### ISSUE TITLE
Bitor and Bitxor functions

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/oos-utils#44]
https://connormcdonald.wordpress.com/2016/02/08/bitwise-operations/

**Comment by martindsouza** [comment]
Add to a `math` package?

**Comment by janihur** [comment]
And a `bitnot` too ?

From http://www.orafaq.com/wiki/Bit

```plsql
CREATE FUNCTION bitnot(x IN NUMBER) RETURN NUMBER AS 
BEGIN
    RETURN (0 - x) - 1;
END;
/
```

**Comment by martindsouza** [comment]
@janihur good idea on the `bitnot`. What do you thin we should call the package? `oos_util_math`, `oos_util_bit`?

**Comment by martindsouza** [comment]
@janihur Thanks for all the PRs!
