### ISSUE TITLE
Get number ordinal

### ISSUE THREAD

**Issue by tschf** [OraOpenSource/oos-utils#53]
Not sure if this is all that common - and I don't believe the to_char format model offers it other than in a date. But still useful. Logic taken from: http://stackoverflow.com/a/13627586/3476713

```plsql
set serveroutput on

declare
    
    function ord(p_num in number)
    return varchar2
    as
        l_mod10 NUMBER;
        l_mod100 NUMBER;
    begin
        l_mod10 := mod(p_num, 10);
        l_mod100 := mod(p_num, 100);
    
        if l_mod10 = 1 and l_mod100 != 11
        then
            return 'st';
        elsif l_mod10 = 2 and l_mod100 != 12
        then
            return 'nd';
        elsif l_mod10 = 3 and l_mod100 != 13
        then
            return 'rd';
        else
            return 'th';
        end if;    
    
    
    end ord;
    
    
begin

    for i in 1..50
    loop
        dbms_output.put_line(i || ord(i));
    end loop;

end;
/
```

Output:

>1st
2nd
3rd
4th
5th
6th
7th
8th
9th
10th
11th
12th
13th
14th
15th
16th
17th
18th
19th
20th
21st
22nd
23rd
24th
25th
26th
27th
28th
29th
30th
31st
32nd
33rd
34th
35th
36th
37th
38th
39th
40th
41st
42nd
43rd
44th
45th
46th
47th
48th
49th
50th

**Comment by martindsouza** [comment]
@tschf do you think this should go into the string package? What should we all the function? `get_ordinal`?

**Comment by tschf** [comment]
String package makes enough sense. 

I called my function `num_ordinal` recently. I think it'd be good to have `num` or similar in the function name so you know it's specifically for a number.

`get_num_ordinal` would be good; or maybe even better would be `get_ordinal_num` and return the number with the ordinal indicator. (1st, 2nd). The example method above only returns the ordinal indicator, which is probably not much use without the number.

**Comment by janihur** [comment]
I think a normal [subprogram overloading](https://docs.oracle.com/cd/B19306_01/appdev.102/b14261/subprograms.htm#i12352) will do. `ordinal` seems to be a proper name. As usual YMMV.

```plsql
-- oos_util_string
-- return p_num postfixed with an ordinal. e.g. p_num = 1 returns '1st'
function ordinal(p_num in number) return varchar2;
```

Does it really makes sense to return `st` instead of `1st` ?

How about negative numbers ?

**Comment by tschf** [comment]
> Does it really makes sense to return st instead of 1st ?

That's what I was trying to allude to in my last reply, returning just `st`, `rd`, etc doesn't make sense.

> How about negative numbers ?

Haddn't really thought about negatives, but I guess you would still want the same ordinal indicator than for it's positive counter part.

**Comment by janihur** [comment]
> That's what I was trying to allude to in my last reply,

Oh, yes you're correct - I see that now.

**Comment by janihur** [comment]
@tschf could you please create a pull request for this ? The function signature I prefer is mentioned earlier. In the documentation mention the ordinal is for English only.

**Comment by tschf** [comment]
Yes, I can do if you need. It'll be at least a couple of weeks before I can
make a PR, as my computer is out of action.
