### ISSUE TITLE
Possible l_warning silently ignored in lob conversions

### ISSUE THREAD

**Issue by janihur** [OraOpenSource/oos-utils#62]
This applies both to `oos_util_lob.clob2blob` and `oos_util_lob.blob2clob`.

Possible warning value (`l_warning` out variable) is ignored in lob conversions. Is this by design ?

```plsql
    dbms_lob.converttoclob(
      dest_lob => l_clob,
      src_blob => p_blob,
      amount => dbms_lob.lobmaxsize,
      dest_offset => l_dest_offsset,
      src_offset => l_src_offsset,
      blob_csid => dbms_lob.default_csid,
      lang_context => l_lang_context,
      warning => l_warning);
```

[Oracle documentation](http://docs.oracle.com/cd/E11882_01/appdev.112/e40758/d_lob.htm#ARPLS603) says:

> Warning message. This parameter indicates when something abnormal happened during the conversion. You are responsible for checking the warning message.
>
>Currently, the only possible warning is — inconvertible character. This occurs when the character in the source cannot be properly converted to a character in destination. The default replacement character (for example, '?') is used in place of the inconvertible character. The return value of this error message is defined as the constant warn_inconvertible_char in the DBMS_LOB package.

In my own implementation I'll check the value and throw:

```plsql
      if v_warning <> dbms_lob.no_warning then
        raise_application_error(-20100,
                                'JH_UTIL: failed to convert clob to blob: ' ||
                                'v_warning = ' || v_warning);  
      end if;
```

However I don't recall I have ever run into this problem.

**Comment by martindsouza** [comment]
@janihur good catch! Want to make a PR with the fix. For the error number just use `-20000`.

**Comment by janihur** [comment]
I'll make a pr.
