### ISSUE TITLE
Create APEX session

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/oos-utils#7]
See http://www.talkapex.com/2012/08/how-to-create-apex-session-in-plsql.html for example

May need to modify for APEX 5.0 as it may not allow for multiple calls for a session to be created.

**Comment by martindsouza** [comment]
Suggestion from Trent: 

I imagine your idea is to create them so you can utilise collections and mail etc outside apex scope. From another view, useful to be able to use views that access session variables? as per http://apextips.blogspot.com.au/2014/10/debugging-parameterised-views-outside.html

**Comment by martindsouza** [comment]
@tschf Good idea on the re-join session. I've created two APIs `create_session` and `join_session`. Let me know what you think. Should we call it `join_session` or `re_join_session`?

**Comment by tschf** [comment]
@martindsouza I prefer `join_session`.
