### ISSUE TITLE
Create development standards docs

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/oos-utils#72]
Based on #68  and PR #70 @janihur made a good point about consistency. Create a doc about the development standards for this project. Try to keep it simple and for now add the following:

- [x] all params start with `p_`
- [x] tab space 2
- [x] all lowercase
- [x] don't unnecessarily space variables

**Comment by janihur** [comment]
@martindsouza can you create a placeholder document with an example structure ? I can then check it and contribute.

**Comment by martindsouza** [comment]
@janihur For now I've put in [https://github.com/OraOpenSource/oos-utils/tree/master/build](https://github.com/OraOpenSource/oos-utils/tree/master/build) as a sub section. We can start there and move depending on how indepth we go.
