### ISSUE TITLE
Change tochar to sys.standard.to_char

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/oos-utils#74]
Allows for consistent naming.

**Comment by janihur** [comment]
The title and description is vague. Could you please confirm you mean this:

```plsql
  -- oos_util_string.pkb
  function to_char(
    p_val in number)
    return varchar2
  as
  begin
    return sys.standard.to_char(p_val);
  end;
```

**Comment by janihur** [comment]
Btw, in my own code I use `to_str` that elegantly (IMO) avoids the issue.

**Comment by martindsouza** [comment]
@janihur Yes that's what I meant. It'll only affect this package.

`sys` is highly recommended. Reason is that their could be either a schema call `standard` or a public synonym for a package called `standard` that we must account for. On a security perspective Oracle recommends prefixing things like `htp` with `sys.htp` so that they're no security vulnerabilities.
