### ISSUE TITLE
assert function

### ISSUE THREAD

**Issue by hg-smart** [OraOpenSource/oos-utils#85]
Hello Martin,

as discussed at the apexConnect the [assert](http://oos-utils.readthedocs.io/en/latest/oos_util/#assert) function is really geat.

1. normally we want to display a nice message to the user, therefore raising an exception is sometimes good sometimes really bad
2. additinally checks are not only performed on a single value, normally on a whole cursor content

To deal with that, i would reccommend that we enchance the function to optionally not raise exceptions, and think about a way to store the exceptions in a plsql table returned as out parameter from the assert funciton

Best
Hansjörg

**Comment by martindsouza** [comment]
@hg-smart It was nice meeting you at APEX connect and I appreciate the feedback.

We will keep the exception block as we do want the program to fail when an assert does not pass. For example if there was a function `update_emp_sal` and `p_empno` is null then we need to stop right away.

Regarding your situation it seems like you need an error handling process around the app as a whole. In general the code should focus on raising errors and not user friendly errors. The application should handle how to display these technical error messages in a user friendly way. Thankfully APEX supports this model with the error handling function. 

Do you think the following will work for you?

- Leave the assert as is with its default error code `-20000`
- For each call to `assert` use some sort of naming scheme that is relevant to you. In the example above you can use a code like: `EMPNO_MISSING`.
- In the APEX error handling function have specific code for `-20000` and then process the code against an error lookup table. There has been some talk about creating such a structure in OOS but for the time being we won't add it in the current release.

Let me know what you think.

**Comment by hg-smart** [comment]
@martindsouza thx.

there are 2 points ..
-- process code against lookup table -> nice to have for me
-- use function for a array of data in a plsql construct, here you are right, we can use the apex function... but of course we want to use the same function for a import process... then a wrapper construct would be helpful, but of course not only apex relevant.

That would be my intention...so up to you, you can close this request and keep my thoughts in mind...

**Comment by martindsouza** [comment]
@hg-smart I've created a new ticket for this #87 I'll close this ticket as no changes to `assert` will be required (as of now)
