### ISSUE TITLE
Is user logged in

### ISSUE THREAD

**Issue by vitodcampanelli** [OraOpenSource/oos-utils#9]
A function that returns if user is logged into the APEX application for added security on third party report engines like:
- PLPDF
- Jasper
- BIRT

**Comment by martindsouza** [comment]
Can you please provide a bit more of an example? Any reason why you couldn't using `v('APP_SESSION`) or something similar?

**Comment by vitodcampanelli** [comment]
I have a function that returns true if the user has a valid APEX session. This works great in PLPDF but not for Jasper. I may just be wishing for the impossible.

``` sql

/**
 * @param p_session_id: The apex sessions id
 * @param p_user_name: The apex user name
 */

SELECT COUNT (*)
        INTO L_SESSION_CNT
        FROM APEX_WORKSPACE_SESSIONS
       WHERE     APEX_SESSION_ID = P_SESSION_ID
             AND USER_NAME = P_USER_NAME
             AND SESSION_CREATED BETWEEN SYSDATE - 1 AND SYSDATE + 1 / 24;

      IF L_SESSION_CNT > 0
      THEN
         L_SESSION_VALID := TRUE;
      END IF;

      RETURN L_SESSION_VALID;
```

**Comment by martindsouza** [comment]
What do you think about this (just for the query, the rest makes sense). *Note: no p_user_name as it's not required with a session_id.*

```sql
select *
from apex_workspace_sessions aws
where 1=1
  and aws.apex_session_id = :p_session_id
  and sysdate <= aws.session_idle_timeout_on
  and sysdate <= aws.session_life_timeout_on  -- Not sure if this one is required
;
```

**Comment by vitodcampanelli** [comment]
I think that works great.

From: martindsouza
Reply-To: OraOpenSource/oos-utils
Date: Saturday, September 5, 2015 at 6:51 PM
To: OraOpenSource/oos-utils
Cc: vitodcampanelli
Subject: Re: [oos-utils] Is user logged in (#9)


What do you think about this (just for the query, the rest makes sense). Note: no p_user_name as it's not required with a session_id.

select *from apex_workspace_sessions aws
where 1=1
  and aws.apex_session_id = :p_session_id
  and sysdate <= aws.session_idle_timeout_on
  and sysdate <= aws.session_life_timeout_on  -- Not sure if this one is required
;

**Comment by martindsouza** [comment]
Note: `apex_custom_auth.is_session_valid` has similar functionality but limited to active session.
